
export enum Motif{
  SOUTIEN_FAMILIAL='SOUTIEN_FAMILIAL',
  INVESTISSEMENT= 'INVESTISSEMENT',
  CADEAU='CADEAU',
  PAIEMENT_DE_BIENS_ET_DE_SERVICES='PAIEMENT_DE_BIENS_ET_DE_SERVICES',
  FRAIS_DE_DÉPASSEMENT='FRAIS_DE_DÉPASSEMENT',
  FRAIS_DE_L_EDUCATION='FRAIS_DE_L_EDUCATION',
  LOCATION='LOCATION',
  MÉDICALE='MÉDICALE',
  REVENU_D_UN_SITE_INTERNET='REVENU_D_UN_SITE_INTERNET',
  DÉPENSES_SALARIALES='DÉPENSES_SALARIALES',
  TAXES='TAXES',
  PRÊT='PRÊT',
  COMMERCE_SUR_INTERNET='COMMERCE_SUR_INTERNET',
  Donation='Donation',
  Autres='Autres'
}
