export enum Motif {
    SOUTIEN_FAMILIAL,
    INVESTISSEMENT,
    CADEAU,
    PAIEMENT_DE_BIENS_ET_DE_SERVICES,
    FRAIS_DE_DÉPASSEMENT,
    FRAIS_DE_L_EDUCATION,
    LOCATION,
    MÉDICALE,
    REVENU_D_UN_SITE_INTERNET,
    DÉPENSES_SALARIALES,
    TAXES,
    PRÊT,
    COMMERCE_SUR_INTERNET,
    Donation,
    Autres
}
